version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      javascript-dependencies:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: "/src-tauri"
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      rust-dependencies:
        patterns:
          - "*"
