#[cfg(test)]
mod tests {
    use std::path::Path;
    use ts_rs::{Config, TS};

    fn push_decl<T: TS>(output: &mut String, config: &Config) {
        output.push_str(&exported_decl::<T>(config));
        output.push_str("\n\n");
    }

    fn exported_decl<T: TS>(config: &Config) -> String {
        let declaration = T::decl(config);
        declaration
            .strip_prefix("type ")
            .map(|rest| format!("export type {rest}"))
            .unwrap_or(declaration)
    }

    fn trim_trailing_whitespace(output: &str) -> String {
        let mut trimmed = output
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n");
        trimmed.push('\n');
        trimmed
    }

    #[test]
    fn export_typescript_bindings() {
        let config = Config::new().with_large_int("number");
        let mut output =
            String::from("// This file is generated by `cargo test export_typescript_bindings`.\n");
        output
            .push_str("// Edit the Rust DTOs and rerun the test instead of editing this file.\n\n");

        push_decl::<crate::settings::Settings>(&mut output, &config);
        push_decl::<crate::db::Wallpaper>(&mut output, &config);
        push_decl::<crate::db::Collection>(&mut output, &config);
        push_decl::<crate::db::CollectionMembership>(&mut output, &config);
        push_decl::<crate::db::SavedFilter>(&mut output, &config);
        push_decl::<crate::db::WallpaperHistoryEntry>(&mut output, &config);
        push_decl::<crate::commands::monitors::Monitor>(&mut output, &config);
        push_decl::<crate::commands::wallpaper_restore::WallpaperBackupStatus>(
            &mut output,
            &config,
        );
        push_decl::<crate::commands::wallpaper_restore::WallpaperRestoreStatus>(
            &mut output,
            &config,
        );
        push_decl::<crate::importing::ImportProbe>(&mut output, &config);
        push_decl::<crate::commands::wallpaper_import::ImportWallpaperResult>(&mut output, &config);
        push_decl::<crate::commands::wallpaper_import::BatchImportItem>(&mut output, &config);
        push_decl::<crate::commands::wallpaper_import_scan::ImportRejectedPath>(
            &mut output,
            &config,
        );
        push_decl::<crate::commands::wallpapers::ImportScanResult>(&mut output, &config);
        push_decl::<crate::commands::wallpaper_import::ImportFailure>(&mut output, &config);
        push_decl::<crate::commands::wallpaper_import::BatchImportResult>(&mut output, &config);
        push_decl::<crate::commands::wallpapers::BrokenWallpaper>(&mut output, &config);
        push_decl::<crate::commands::wallpaper_import::ThumbnailRegenerationResult>(
            &mut output,
            &config,
        );
        push_decl::<crate::commands::wallpaper_library::RemoveWallpaperResult>(
            &mut output,
            &config,
        );
        push_decl::<crate::motionbgs::MotionBgsDownloadOption>(&mut output, &config);
        push_decl::<crate::motionbgs::MotionBgsWallpaper>(&mut output, &config);
        push_decl::<crate::motionbgs::MotionBgsMeta>(&mut output, &config);
        push_decl::<crate::motionbgs::MotionBgsSearchResponse>(&mut output, &config);
        push_decl::<crate::commands::motionbgs::MotionBgsSearchArgs>(&mut output, &config);
        push_decl::<crate::commands::motionbgs::DownloadMotionBgsResult>(&mut output, &config);
        push_decl::<crate::wallhaven::WallhavenThumbs>(&mut output, &config);
        push_decl::<crate::wallhaven::WallhavenWallpaper>(&mut output, &config);
        push_decl::<crate::wallhaven::WallhavenMeta>(&mut output, &config);
        push_decl::<crate::wallhaven::WallhavenSearchResponse>(&mut output, &config);
        push_decl::<crate::commands::wallhaven::WallhavenSearchArgs>(&mut output, &config);
        push_decl::<crate::commands::wallhaven::DownloadWallhavenResult>(&mut output, &config);
        push_decl::<crate::downloads::DownloadProgressEvent>(&mut output, &config);
        push_decl::<crate::commands::runtime::RuntimeStatus>(&mut output, &config);
        push_decl::<crate::storage::StorageStats>(&mut output, &config);
        push_decl::<crate::storage::StorageCleanupResult>(&mut output, &config);

        let output_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../src/lib/types/generated.ts")
            .canonicalize()
            .unwrap_or_else(|_| {
                Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/types/generated.ts")
            });

        std::fs::write(&output_path, trim_trailing_whitespace(&output)).unwrap_or_else(|error| {
            panic!(
                "failed to write generated TypeScript bindings to {}: {}",
                output_path.display(),
                error
            )
        });
    }
}
