// This file is generated by `cargo test export_typescript_bindings`.
// Edit the Rust DTOs and rerun the test instead of editing this file.

export type Settings = {
/**
 * Launch Wallscape automatically when the user signs in to Windows.
 */
launchAtStartup: boolean,
/**
 * Start hidden in the system tray instead of showing the main window.
 */
startMinimized: boolean,
/**
 * Closing the window hides it to the tray instead of quitting the app.
 */
closeToTray: boolean,
/**
 * Minimizing the window hides it to the tray instead of the taskbar.
 */
minimizeToTray: boolean,
/**
 * Re-apply the most recently used video wallpaper on launch.
 */
restoreLastWallpaper: boolean,
/**
 * Rotate through favorite wallpapers on a timer while Wallscape is running.
 */
favoriteRotationEnabled: boolean,
/**
 * Minutes between automatic favorite wallpaper rotations.
 */
favoriteRotationIntervalMinutes: number,
/**
 * Apply a random favorite wallpaper when Wallscape starts.
 */
favoriteRotationOnStartup: boolean,
/**
 * Automatically pause live wallpapers when selected rules match.
 */
autoPauseEnabled: boolean,
/**
 * Pause live wallpapers while the machine is running on battery power.
 */
autoPauseOnBattery: boolean,
/**
 * Pause live wallpapers while a fullscreen foreground app is active.
 */
autoPauseFullscreenApps: boolean,
/**
 * Pause live wallpapers while every monitor is covered by other windows.
 */
autoPauseOccluded: boolean,
/**
 * Pause live wallpapers while the session is remote desktop.
 */
autoPauseRemoteSession: boolean,
/**
 * Pause live wallpapers when the interactive desktop is unavailable.
 */
autoPauseDisplaySleep: boolean,
/**
 * Default playback speed for video wallpapers (0.25x to 2.0x).
 */
defaultPlaybackSpeed: number,
/**
 * Default video fit mode for wallpapers: "fit", "fill", or "stretch".
 */
defaultFitMode: string,
/**
 * Default FPS cap for video wallpapers (None = uncapped).
 */
defaultFpsCap: number | null, };

export type Wallpaper = { id: number, title: string, file_path: string, thumbnail_path: string | null, tags: Array<string>, width: number, height: number, fps: number, duration_ms: number, file_size_bytes: number, created_at: number, media_type: string, source: string | null, source_id: string | null, is_favorite: boolean, };

export type Collection = { id: number, name: string, created_at: number, wallpaper_count: number, };

export type CollectionMembership = { collection_id: number, wallpaper_id: number, };

export type SavedFilter = { id: number, name: string, filter_type: string, payload: string, created_at: number, };

export type WallpaperHistoryEntry = { id: number, wallpaper_id: number | null, title: string, file_path: string, thumbnail_path: string | null, media_type: string, target_monitor_id: string | null, apply_source: string, applied_at: number, };

export type Monitor = { id: string, name: string, x: number, y: number, width: number, height: number, is_primary: boolean, };

export type WallpaperBackupStatus = { path: string | null, can_restore: boolean, };

export type WallpaperRestoreStatus = { path: string | null, can_restore: boolean, };

export type ImportProbe = { width: number | null, height: number | null, fps: number | null, durationMs: number | null, thumbnailDataUrl: string | null, warnings: Array<string> | null, };

export type ImportWallpaperResult = { wallpaper: Wallpaper, warnings: Array<string>, duplicate: boolean, };

export type BatchImportItem = { videoPath: string, probe: ImportProbe | null, };

export type ImportRejectedPath = { path: string, reason: string, };

export type ImportScanResult = { files: Array<string>, rejected: Array<ImportRejectedPath>, };

export type ImportFailure = { path: string, reason: string, };

export type BatchImportResult = { imported: Array<Wallpaper>, duplicates: Array<Wallpaper>, failed: Array<ImportFailure>, warnings: Array<string>, };

export type BrokenWallpaper = { wallpaper: Wallpaper, reason: string, };

export type ThumbnailRegenerationResult = { wallpaper: Wallpaper, warnings: Array<string>, };

export type RemoveWallpaperResult = { wallpaper: Wallpaper, };

export type MotionBgsDownloadOption = { quality: string, url: string, width: number, height: number, fileSize: number, };

export type MotionBgsWallpaper = { id: string, slug: string, title: string, url: string, thumbnailUrl: string, previewVideoUrl: string | null, quality: string, width: number, height: number, fileSize: number, tags: Array<string>, downloads: Array<MotionBgsDownloadOption>, };

export type MotionBgsMeta = { currentPage: number, hasNextPage: boolean, };

export type MotionBgsSearchResponse = { data: Array<MotionBgsWallpaper>, meta: MotionBgsMeta, };

export type MotionBgsSearchArgs = { query: string | null, category: string | null, page: number | null, };

export type DownloadMotionBgsResult = { wallpaper: Wallpaper, sourceId: string, };

export type WallhavenThumbs = { large: string, original: string, small: string, };

export type WallhavenWallpaper = { id: string, url: string, short_url: string, views: number, favorites: number, purity: string, category: string, dimension_x: number, dimension_y: number, resolution: string, ratio: string, file_size: number, file_type: string, created_at: string, colors: Array<string>, path: string, thumbs: WallhavenThumbs, };

export type WallhavenMeta = { current_page: number, last_page: number, per_page: number, total: number, seed: string | null, };

export type WallhavenSearchResponse = { data: Array<WallhavenWallpaper>, meta: WallhavenMeta, };

export type WallhavenSearchArgs = { query: string | null, categories: string | null, purity: string | null, sorting: string | null, order: string | null, atleast: string | null, ratios: string | null, page: number | null, };

export type DownloadWallhavenResult = { wallpaper: Wallpaper, sourceId: string, };

export type DownloadProgressEvent = { source: string, sourceId: string, downloadKey: string, status: string, attempt: number, receivedBytes: number, totalBytes: number | null, progress: number | null, message: string | null, };

export type RuntimeStatus = {
/**
 * A video wallpaper is currently running.
 */
active: boolean,
/**
 * The active wallpaper is paused.
 */
paused: boolean,
/**
 * The active wallpaper is currently paused by an automatic rule.
 */
autoPaused: boolean, };

export type StorageStats = { total_cache_bytes: number, wallhaven_cache_bytes: number, wallhaven_cache_files: number, unused_wallhaven_cache_bytes: number, unused_wallhaven_cache_files: number, wallhaven_library_entries: number, thumbnail_cache_bytes: number, thumbnail_cache_files: number, unused_thumbnail_bytes: number, unused_thumbnail_files: number, missing_library_entries: number, };

export type StorageCleanupResult = { removed_files: number, removed_bytes: number, removed_entries: number, warnings: Array<string>, };
